# action.yml
name: "Validate Dart/Flutter package"
description: "Validate Dart/Flutter package"
inputs:
  flutter_package:
    description: "(Optional) Code packages type.  Set to false if this is a pure dart package. (default: true)"
    required: false
    default: true
  package_directory:
    description: '(Optional) Package directory (default: ".")'
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "arrow-up-circle"
  color: "blue"
