# action.yml
name: "Publish Dart/Flutter package"
description: "Publish Dart/Flutter package"
inputs:
  channel:
    description: "(Optional) Flutter / Dart channel to use (default: stable"
    required: false
    default: "stable"
  path:
    description: '(Optional) Package directory (default: ".")'
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: ${{ inputs.channel }}

    - name: Publish
      shell: bash
      id: publish
      run: |
        cat <<EOF > $PUB_CACHE/credentials.json
          ${{ input.credentials }}
          EOF        
        dart format --set-exit-if-changed lib test

        if "${{ inputs.flutter_package }}"; then
          flutter packages get
          flutter analyze
          flutter test
        else
          pub get
          dart analyze
          dart test
        fi
      working-directory: ${{ inputs.path }}
