# action.yml
name: 'Validate Dart/Flutter package'
description: 'Validate Dart/Flutter package'
inputs:
  channel:
    description: '(Optional) Flutter / Dart channel to use (default: stable'
    required: false
    default: 'stable'
  flutter_version:
    description: '(Optional) Flutter version to use'
    default: 'any'
    required: false
  generate_code:
    description: '(Optional) Flag to state whether or not to run the code generator.'
    default: 'false'
    required: false
  path:
    description: '(Optional) Package directory (default: ".")'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs.channel }}
        flutter-version: ${{ inputs.flutter_version }}

    - name: Validate
      shell: bash
      id: validate
      run: |

        dart format --set-exit-if-changed lib test

        if grep -q flutter: "pubspec.yaml"; then 
          flutter packages get
          if test "${{ inputs.generate_code }}" = "true"; then
            dart run build_runner build --delete-conflicting-outputs -v
          fi
          flutter analyze
          flutter test
        else
          dart pub get
          if test "${{ inputs.generate_code }}" = "true"; then
            dart run build_runner build --delete-conflicting-outputs -v
          fi
          dart analyze lib
          dart test
        fi
      working-directory: ${{ inputs.path }}
