name: 'actions_flutter_validate'
description: 'Metadata to provide a version number to the autotagging script'
version: '1.4.0'
homepage: 'https://github.com/peiffer-innovations/actions-flutter-validate'

environment:
  sdk: '>=3.0.0 <4.0.0'
