name: 'actions_flutter_validate'
description: 'Simple CLI to be able to validate Dart and Flutter repos'
version: '2.0.3'
homepage: 'https://github.com/peiffer-innovations/actions-flutter-validate'

environment:
  sdk: '>=3.0.0 <4.0.0'
