name: Tag

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: peiffer-innovations/actions-dart-version-autotag@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
